### PR TITLE
Move to a strategy of targeting a grails version by branch version

### PR DESCRIPTION
**Pull request by jdaugherty**
@sbglasius I'm doing cleanup on the repo to start.  This change:

1. Removes the older grails versions from the 6.0.x branch - the idea is we would create branches for the older versions if we need to do a prior release.  Moves the grails6/* files to the root.
2. Update references to vsachinv & sheehan to be this repo instead.
3. Fixes the publish action so that it invokes the right gradle task.
4. Adds `Sachin Verma` to the README.md since they were added to `ConsoleGrailsPlugin.groovy`
5. Adds `.sdkmanrc` to define the java version used by default in development.

I was going to suggest after merging this that we enable publishing to the grails repo like the other projects.  Then we can update to grails 7.

### CODE REVIEW

**Comment by codeconsole** [comment]
`ConsoleGrailsPlugin` -> `WebConsoleGrailsPlugin`

**Review by codeconsole — CHANGES_REQUESTED** [review]
Plugin should now resolve to grails-web-console because it causes confusion with the console plugin

**Comment by codeconsole** [comment]
We also need a build and snapshot publish actions.  [Use this ](https://github.com/gpc/fields/blob/5.1.x/.github/workflows/gradle.yml), but update to Liberica.   Update it to run all the tests.

**Comment by codeconsole** [comment]
Change the version from `version=6.0-M2` to `version=6.0.0-SNAPSHOT`

**Comment by codeconsole** [comment]
Can you update the wrapper to 8.10.2?

**Comment by jdaugherty** [comment]
> Can you update the wrapper to 8.10.2?

I was going to wait until 7.0.x for the Grails 7 compatibility.  So far this is just getting a release for Grails 6.

**Comment by jdaugherty** [comment]
Everything but the gradle upgrade is done.  I'd say we merge this so we can start work on the 7.0.x build.  We also need to make the 6.0.x branch the default for now.

**Pull request merged**
